
'use client';
import Head from 'next/head'
// import Curve from '@/components/Layout/Curve'
// import styles from './page.module.scss'
import { useEffect, useRef, useState } from 'react'
import { AnimatePresence } from 'framer-motion';
import Preloader from '../components/Preloader';
import Landing from '../components/Landing';
import Projects from '../components/Projects';
import { gsap } from 'gsap';
// import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import AnimationContext from '../common/contexts/animation-context';


export default function Home() {

  const [isLoading, setIsLoading] = useState(true);

  const [currentBg, setCurrentBg] = useState('#000')
  let appRef = useRef(null);

  useEffect( () => {
    (
      async () => {
          const LocomotiveScroll = (await import('locomotive-scroll')).default
          const locomotiveScroll = new LocomotiveScroll();

          setTimeout( () => {
            setIsLoading(false);
            document.body.style.cursor = 'default'
            window.scrollTo(0,0);
          }, 1000)
      }
    )
    ()
  }, []);



  useEffect( () => {
    
    gsap.to(appRef.current, {
      duration: 1,
      background: currentBg,
    })

    
  }, [currentBg]);



  return (
    <>
      <Head>
        <title>Sopiriye Jamabo - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence mode='wait'>
        {isLoading && <Preloader />}
      </AnimatePresence>
      {/* <Curve backgroundColor={"#B0AD98"}> */}
  
  
<AnimationContext.Provider value={{ setCurrentBg }}>
      <div ref={appRef} className="">
  <Landing />
 <Projects  />
 </div>
 </AnimationContext.Provider>
   
      {/* </Curve> */}
    </>
  )
}



